/* fonts */
export const FontFamily = {
    lexendSemiBold: "Lexend-SemiBold",
    manropeBold: "Manrope-Bold",
    manropeRegular: "Manrope-Regular",
    poppinsBlack: "Poppins-Black",
    manropeExtraBold: "Manrope-ExtraBold",
    poppinsRegular: "Poppins-Regular",
    poppinsBold: "Poppins-Bold",
    lexendRegular: "Lexend-Regular",
    fredokaOne: "Fredoka One",
    poppinsExtraBold: "Poppins-ExtraBold",
    fredokaSemiBold: "Fredoka-SemiBold",
    poppinsSemiBold: "Poppins-SemiBold",
    lexendBold: "Lexend-Bold",
    manropeSemiBold: "Manrope-SemiBold",
    manropeLight: "Manrope-Light",
    manropeMedium: "Manrope-Medium",
    fredokaRegular: "Fredoka-Regular",
    fredokaMedium: "Fredoka-Medium",
  };
  /* font sizes */
  export const FontSize = {
    size_sm: 14,
    size_xs: 12,
    size_lg: 18,
    size_5xl: 24,
    size_3xs: 10,
    size_2xs: 11,
    size_base: 16,
    size_xl: 20,
    size_45xl: 64,
    size_13xl: 32,
    size_4xs: 9,
    size_5xs: 8,
    size_6xl: 25,
  };
  /* Colors */
  export const Color = {
    colorWhite: "#fff",
    colorGray_100: "#fafafb",
    colorGray_200: "#171a1f",
    colorGray_300: "rgba(255, 255, 255, 0.5)",
    colorGray_400: "rgba(0, 0, 0, 0)",
    colorBlack: "#000",
    colorGainsboro_100: "#dee1e6",
    colorDarkslategray_100: "#424956",
    colorDarkslategray_200: "#323842",
    colorDarkorange: "#ff8a1f",
    colorWhitesmoke_100: "#f8f9fa",
    colorWhitesmoke_200: "#f3f4f6",
    colorDimgray: "#565e6d",
    colorLightslategray: "#9095a0",
    colorSilver_100: "#bcc1ca",
    colorPaleturquoise: "rgba(151, 231, 225, 0.17)",
    colorMediumturquoise_100: "#6ad4dd",
  };
  /* border radiuses */
  export const Border = {
    br_21xl: 40,
    br_sm: 14,
    br_lg: 18,
    br_xs: 12,
    br_29xl: 48,
    br_95xl: 114,
    br_3xl: 22,
    br_8xs_5: 5,
    br_7xs_5: 6,
    br_mini: 15,
    br_3xs: 10,
    br_81xl: 100,
  };
  